[package]
name = "moderntensor"
version = "1.0.0"

[addresses]
moderntensor = "67df0f3952c20d5e95e84d6ca7dd2915b578df6dcd2825671f657cc16059acb3" 
tests = "0x1" # hoặc một địa chỉ ảo khác như 0x42
[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core", subdir = "aptos-move/framework/aptos-stdlib", rev = "main" }
