[package]
name = "moderntensor"
version = "1.0.0"

[addresses]
moderntensor = "2f2bf81dc637cd21143c90e643e8853547e0f511154397411dd01966c12a0b08" 
tests = "0x1" # hoặc một địa chỉ ảo khác như 0x42
[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core", subdir = "aptos-move/framework/aptos-stdlib", rev = "main" }
